import { addDays, addHours } from 'date-fns';
import { AdminUser, Category, EventItem, ReminderItem, TelegramImport } from '@/lib/types';

const now = new Date();

export const mockCategories: Category[] = [
  { id: 'cat-1', title: '54-ФЗ', slug: '54-fz', color: '#0f766e', _count: { events: 3 } },
  { id: 'cat-2', title: 'Онлайн-кассы', slug: 'online-kassy', color: '#0ea5a4', _count: { events: 2 } },
  { id: 'cat-3', title: '1С и автоматизация', slug: '1c-auto', color: '#1d4ed8', _count: { events: 4 } },
  { id: 'cat-4', title: 'Маркировка и ЕГАИС', slug: 'markirovka-egais', color: '#7c3aed', _count: { events: 2 } },
];

export const mockEvents: EventItem[] = [
  {
    id: 'event-1',
    title: 'Практикум: изменения 54-ФЗ в 2026 году',
    slug: 'praktikum-izmeneniya-54-fz-2026',
    descriptionShort: 'Разбор новых требований, чеков коррекции и частых ошибок бухгалтерии.',
    descriptionFull: 'Подробный вебинар для бухгалтеров и руководителей аутсорсинговых компаний: изменения 54-ФЗ, ответственность, корректировка расчетов, кейсы по торговым точкам и интеграциям касс.',
    startAt: addDays(now, 2).toISOString(),
    endAt: addDays(addHours(now, 2), 2).toISOString(),
    location: 'Онлайн / Zoom',
    format: 'ONLINE',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
    source: 'MANUAL',
    sourceUrl: 'https://t.me/ab_afisha_buh',
    isImportant: true,
    status: 'SCHEDULED',
    runtimeStatus: 'SCHEDULED',
    published: true,
    tags: ['54-ФЗ', 'кассы', 'отчетность'],
    category: mockCategories[0],
    _count: { reminders: 42 },
  },
  {
    id: 'event-2',
    title: 'Встреча: онлайн-кассы, ОФД и интеграция с 1С',
    slug: 'vstrecha-kassy-ofd-1c',
    descriptionShort: 'Покажем связку касса + ОФД + товароучет + 1С без ручных разрывов.',
    descriptionFull: 'Живая встреча по настройке торгового контура: онлайн-касса, ОФД, 1С, МойСклад, приемка, возвраты, продажи и сверка документов.',
    startAt: addDays(now, 5).toISOString(),
    endAt: addDays(addHours(now, 3), 5).toISOString(),
    location: 'Тюмень, бизнес-пространство АБ Партнер',
    format: 'HYBRID',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop',
    source: 'TELEGRAM',
    sourceUrl: 'https://t.me/ab_afisha_buh',
    isImportant: true,
    status: 'SCHEDULED',
    runtimeStatus: 'SCHEDULED',
    published: true,
    tags: ['ОФД', '1С', 'интеграция'],
    category: mockCategories[1],
    _count: { reminders: 18 },
  },
  {
    id: 'event-3',
    title: 'Интенсив: Честный Знак, ЕГАИС и маркировка',
    slug: 'intensiv-chestnyi-znak-egais',
    descriptionShort: 'Актуальная практика по маркировке, алкогольному контуру и отчетам.',
    descriptionFull: 'Покрываем процессы работы с маркированной продукцией, фиксацией в ЕГАИС, возвратами, приемкой и автоматизацией для учетных команд.',
    startAt: addDays(now, -1).toISOString(),
    endAt: addHours(now, 1).toISOString(),
    location: 'Онлайн',
    format: 'ONLINE',
    imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?q=80&w=1200&auto=format&fit=crop',
    source: 'TELEGRAM',
    sourceUrl: 'https://t.me/ab_afisha_buh',
    isImportant: false,
    status: 'LIVE',
    runtimeStatus: 'LIVE',
    published: true,
    tags: ['ЕГАИС', 'маркировка'],
    category: mockCategories[3],
    _count: { reminders: 11 },
  },
  {
    id: 'event-4',
    title: 'Обучение: 1С для бухгалтеров торговых компаний',
    slug: 'obuchenie-1c-dlya-bukhgalterov-torgovykh-kompanii',
    descriptionShort: 'Настройка обмена, документооборот и контроль первички в 1С.',
    descriptionFull: 'Практический модуль по настройке справочников, обменов, чеков, остатков, отчетов и бизнес-процессов в 1С с учетом торговых интеграций.',
    startAt: addDays(now, 8).toISOString(),
    endAt: addDays(addHours(now, 4), 8).toISOString(),
    location: 'Онлайн',
    format: 'ONLINE',
    imageUrl: 'https://images.unsplash.com/photo-1554224154-26032fced8bd?q=80&w=1200&auto=format&fit=crop',
    source: 'MANUAL',
    sourceUrl: 'https://ab-partner.ru',
    isImportant: false,
    status: 'SCHEDULED',
    runtimeStatus: 'SCHEDULED',
    published: false,
    tags: ['1С', 'автоматизация'],
    category: mockCategories[2],
    _count: { reminders: 9 },
  },
];

export const mockImports: TelegramImport[] = [
  {
    id: 'import-1',
    sourcePostId: '1781',
    sourceUrl: 'https://t.me/ab_afisha_buh/1781',
    rawText: 'Вебинар: 54-ФЗ и кассовая дисциплина\n02.04.2026 11:00\nОнлайн\nРазбор изменений и ошибок.',
    parsedTitle: 'Вебинар: 54-ФЗ и кассовая дисциплина',
    parsedStartAt: addDays(now, 3).toISOString(),
    parsedLocation: 'Онлайн',
    parsedDescription: 'Разбор изменений и ошибок.',
    status: 'NEW',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'import-2',
    sourcePostId: '1780',
    sourceUrl: 'https://t.me/ab_afisha_buh/1780',
    rawText: 'Семинар по 1С и автоматизации торговли...',
    parsedTitle: 'Семинар по 1С и автоматизации торговли',
    parsedStartAt: addDays(now, 6).toISOString(),
    parsedLocation: 'Гибрид',
    parsedDescription: 'Интеграции касс и учета.',
    status: 'REVIEW',
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
];

export const mockReminders: ReminderItem[] = [
  {
    id: 'rem-1',
    telegramUserId: '41234567',
    telegramUsername: 'buhgalter_nina',
    remindBefore: '1h',
    isActive: true,
    createdAt: now.toISOString(),
    event: { id: mockEvents[0].id, title: mockEvents[0].title, startAt: mockEvents[0].startAt, location: mockEvents[0].location },
  },
  {
    id: 'rem-2',
    telegramUserId: '49876543',
    telegramUsername: 'ofd_expert',
    remindBefore: '15m',
    isActive: true,
    createdAt: now.toISOString(),
    event: { id: mockEvents[1].id, title: mockEvents[1].title, startAt: mockEvents[1].startAt, location: mockEvents[1].location },
  },
];

export const mockUsers: AdminUser[] = [
  { id: 'user-1', name: 'Николай Баженов', email: 'admin@ab-partner.ru', role: 'SUPERADMIN', createdAt: now.toISOString() },
  { id: 'user-2', name: 'Елена Соколова', email: 'editor@ab-partner.ru', role: 'ADMIN', createdAt: now.toISOString() },
];
